jobs:
    include:
     - stage: Index pages to Algolia
       language: ruby
       cache: bundler
       before_install:
        - gem install bundler
       rvm:
        - 2.4
       script: |
        bundle install
        bundle exec jekyll algolia