name: Test Drive

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Readable Readme
      uses: tianhaoz95/readable-readme@v0.1.7-alpha
      env:
        RRLOG: true
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
      
